CREATE TABLE USER
(
	ID int AUTO_INCREMENT PRIMARY KEY NOT NULL ,
	ACCOUNT_ID VARCHAR(100),
	NAME VARCHAR(50),
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
	TOKEN CHAR(36),
	BIO VARCHAR(256),
	AVATAR_URL VARCHAR(100)
);

